### ISSUE TITLE
Are rotate_left/right/swap_bytes methods possible?

### ISSUE THREAD

**Issue by TheIronBorn** [rust-lang-nursery/stdsimd#419] opened 2018-04-10 05:36 UTC
I'm curious what it would take to get functionality like integer primitives' methods.

**Comment by TheIronBorn** [comment] 2018-04-10 06:02
I'm also curious about `swap_bytes` and others.  How many of the missing primitive methods are possible to implement here?

**Comment by gnzlbg** [comment] 2018-04-10 06:07
Sine one can easily perform these using shuffles, I think the question is rather whether it is worth it to implement these. Is there an ISA that supports them?

**Comment by TheIronBorn** [comment] 2018-04-10 08:57
To be clear, I want to rotate each lane. Not shuffle the lanes around.

**Comment by gnzlbg** [comment] 2018-04-10 09:12
> To be clear, I want to rotate each lane

I see. In the meantime you can manually implement rotates using bitwise operators, shifts, and splat:

```rust
#![feature(stdsimd)]
use std::simd::*;
fn rotate_left(x: u32x4, n: u32) -> u32x4 {
    let n = n % 32;
    (x << n) | (x >> (32 - n) % 32)
}
```

(note that `vector << n` currently means `vector << splat(n)`, but this behavior will be deprecated soon and one will need to use splat in the near future)

> Not shuffle the lanes around.

The problem is that "rotate left" is both an operation on the primitive type (e.g. `u32` above), and an operation on a sequence of element types (e.g. `&mut [u32]`). Both operations are equally reasonable things to want to do on vector types so we can't really give them the same names. Until now the naming schemes used try to reduce the friction of vertical operations, so I think using `rotate_{left,right}` for vertical operations and something else for the horizontal operations makes sense (e.g. `rotate_elements_{left,right}`).

For `swap_bytes` I don't know which names would be good.

> I'm curious what it would take to get functionality like integer primitives' methods.

Somebody sending a PR with a tested implementation might just be enough. From there to having these land on stable Rust, a mini-FCP might be enough as well.

**Comment by TheIronBorn** [comment] 2018-06-25 23:11
pull request here https://github.com/rust-lang-nursery/stdsimd/pull/496

**Comment by TheIronBorn** [comment] 2018-06-29 17:28
We need `swap_bytes_horizontally` for rand, should I make a PR here or implement it in rand? https://github.com/pitdicker/rand/pull/1

**Comment by TheIronBorn** [comment] 2018-06-29 18:36
Oh I was thinking to use shuffles. Would `llvm.bswap` be better?

**Comment by gnzlbg** [comment] 2018-06-29 18:41
Indeed, shuffles should definitely work. I don't know if `llvm.bswap` would be better (maybe @rkruppe knows). For the portable vector types, you can define a trait in the `codegen` module and implementing for each type using shuffles, and then the macro just calls the trait (e.g. check how it works for `sqrt`). We can then choose to use shuffles or `bswap` for each type independently.

**Comment by rkruppe** [comment] 2018-06-29 19:05
I have little context but ISTM that element-wise bswap is quite a different operation from "interpret the vector as a huge integer and bswap that". But even if I'm mistaken about that, huge integer types like i256 and i512 (and even i128 to a lesser degree) have very spotty support in most backends even functionality-wise, let alone in terms of performance optimizations. Shuffles OTOH sound great. Except:

> Just keep in mind that llvm.bswap only works for integers, not vectors, so you are going to have to cast the 256-bit and 512-bit vectors to i256 and i512 somehow..

Where'd you get that idea? https://godbolt.org/g/NG6Gxu

**Comment by gnzlbg** [comment] 2018-06-29 19:10
I got it from the LLVM LangRef :/

**Comment by TheIronBorn** [comment] 2018-06-29 21:09
Swap bytes PR https://github.com/rust-lang-nursery/stdsimd/issues/509

**Comment by gnzlbg** [comment] 2018-06-30 09:48
@rkruppe https://llvm.org/docs/LangRef.html#llvm-bswap-intrinsics doesn't mention vectors, only integers :/

**Comment by rkruppe** [comment] 2018-06-30 10:03
That's curious, spot checking. But I'm inclined to say it's a docs bug (that someone could report to get clarity) since most similar intrinsics can be applied to vectors "by default" and vector-bswap [even has target-independent tests](https://github.com/llvm-mirror/llvm/blob/4604874612fa292ab4c49f96aedefdf8be1ff27e/test/CodeGen/Generic/bswap.ll).

**Comment by gnzlbg** [comment] 2018-07-02 08:15
I've reported the bug: https://bugs.llvm.org/show_bug.cgi?id=38012

**Comment by gnzlbg** [comment] 2018-07-19 00:08
This is fixed in https://github.com/gnzlbg/packed_simd

**Closed by gnzlbg** 2018-07-19 00:08 UTC
Labels: A-portable
