### ISSUE TITLE
#[target_feature] produces unused attribute warnings

### ISSUE THREAD

**Issue by gnzlbg** [rust-lang-nursery/stdsimd#431] opened 2018-04-19 21:55 UTC
With nightly there are thousands of unused attribute warnings:

```shell
warning: unused attribute
  --> crates/coresimd/src/../../../coresimd/x86_64/sse41.rs:29:1
   |
29 | #[target_feature(enable = "sse4.1")]
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

warning: unused attribute
  --> crates/coresimd/src/../../../coresimd/x86_64/sse42.rs:17:1
   |
17 | #[target_feature(enable = "sse4.2")]
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

warning: unused attribute
  --> crates/coresimd/src/../../../coresimd/x86_64/xsave.rs:35:1
   |
35 | #[target_feature(enable = "xsave")]
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

warning: unused attribute
  --> crates/coresimd/src/../../../coresimd/x86_64/xsave.rs:55:1
   |
55 | #[target_feature(enable = "xsave")]
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

warning: unused attribute
```

@alexcrichton could you look into that?

**Comment by Cocalus** [comment] 2018-04-19 22:07
I was just about to post this as well. to make things, it's inconsistent whether the errors appear or not.
```rust
#[cfg(target_arch = "x86_64")]
use std::arch::x86_64::*;

#[inline]
#[cfg(target_arch = "x86_64")]
// This target feature should be required
#[target_feature(enable = "bmi2")]
unsafe fn bits_31and63_bmi2(v: u64) -> u64 {
    _pext_u64(v, 1 << 31 | 1 << 63)
}

#[inline]
fn bits_31and63_portable(v: u64) -> u64 {
    v >> 31 & 1 | v >> 62 & 2
}

fn bits_31and63(v: u64) -> u64 {
    #[cfg(target_arch = "x86_64")]
    {
        if is_x86_feature_detected!("bmi2") {
            return unsafe { bits_31and63_bmi2(v) };
        }
    }
    bits_31and63_portable(v)
}

fn main() {
    use std::io;

    let mut input_text = String::new();
    io::stdin()
        .read_line(&mut input_text)
        .expect("failed to read from stdin");

    let trimmed = input_text.trim();
    match trimmed.parse::<u64>() {
        //Ok(i) => println!("{} {}", i, bits_31and63(i)),
        Ok(i) => println!("{} {}", i, bits_31and63(i)),
        Err(..) => println!("{} is not a integer", trimmed),
    };
}
```

```shell
$  cargo build
   Compiling stdsimd-bug6 v0.1.0 (*paths removed*)
warning: unused attribute
 --> src/main.rs:7:1
  |
7 | #[target_feature(enable = "bmi2")]
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: #[warn(unused_attributes)] on by default

    Finished dev [unoptimized + debuginfo] target(s) in 1.32 secs
$ cargo clean && cargo build
   Compiling stdsimd-bug6 v0.1.0 (*paths removed*)
    Finished dev [unoptimized + debuginfo] target(s) in 1.62 secs
```

**Comment by alexcrichton** [comment] 2018-04-19 22:12
Ah thanks for the reproduction @Cocalus! Looks like this is related to incremental compilation, I'll take a look.

**Comment by alexcrichton** [comment] 2018-04-20 00:47
I believe I've minimized this to https://github.com/rust-lang/rust/issues/50095

**Comment by alexcrichton** [comment] 2018-05-01 03:12
This should be fixed now

**Closed by alexcrichton** 2018-05-01 03:12 UTC
