### ISSUE TITLE
`stdsimd` fails to build with `target_cpu=skylake-avx512`

### ISSUE THREAD

**Issue by hdevalence** [rust-lang-nursery/stdsimd#157] opened 2017-10-27 17:08 UTC
When compiling `stdsimd` with `rustc 1.22.0-nightly (b7960878b 2017-10-18)` and `-C target_cpu=skylake-avx512`, the build fails:

```
$ RUSTFLAGS="-C target_cpu=skylake-avx512" cargo build --release
   Compiling stdsimd v0.0.2 (file:///<stripped>/stdsimd)
LLVM ERROR: Cannot select: t83: v32i16 = X86ISD::VINSERT t82, t78, Constant:i64<0>
  t82: v32i16 = bitcast t81
    t81: v16i32 = BUILD_VECTOR Constant:i32<0>, Constant:i32<0>, Constant:i32<0>, Constant:i32<0>, Constant:i32<0>, Constant:i32<0>, Constant:i32<0>, Constant:i32<0>, Constant:i32<0>, Constant:i32<0>, Constant:i32<0>, Constant:i32<0>, Constant:i32<0>, Constant:i32<0>, Constant:i32<0>, Constant:i32<0>
      t80: i32 = Constant<0>
      t80: i32 = Constant<0>
      t80: i32 = Constant<0>
      t80: i32 = Constant<0>
      t80: i32 = Constant<0>
      t80: i32 = Constant<0>
      t80: i32 = Constant<0>
      t80: i32 = Constant<0>
      t80: i32 = Constant<0>
      t80: i32 = Constant<0>
      t80: i32 = Constant<0>
      t80: i32 = Constant<0>
      t80: i32 = Constant<0>
      t80: i32 = Constant<0>
      t80: i32 = Constant<0>
      t80: i32 = Constant<0>
  t78: i16 = truncate t5
    t5: i64,ch = CopyFromReg t0, Register:i64 %vreg2
      t4: i64 = Register %vreg2
  t79: i64 = Constant<0>
In function: _ZN61_$LT$stdsimd..v512..u16x32$u20$as$u20$core..fmt..LowerHex$GT$3fmt17h59e1149cebeaa07fE
error: Could not compile `stdsimd`.

To learn more, run the command again with --verbose.
```

**Comment by hdevalence** [comment] 2017-10-27 17:10
Discussion moved from comments here: https://github.com/rust-lang-nursery/stdsimd/issues/146#issuecomment-339495660 and here https://github.com/rust-lang-nursery/stdsimd/issues/146#issuecomment-340008954

**Comment by hdevalence** [comment] 2017-10-27 17:19
@alexcrichton re https://github.com/rust-lang-nursery/stdsimd/issues/146#issuecomment-340008954 , one motivation is to have SSE2/AVX2 code written using intrinsics be able to use the extra registers `xmm16..xmm31`, `ymm16..ymm31` that AVX512VL provides.  Is this possible using feature detection?

**Comment by alexcrichton** [comment] 2017-10-30 14:43
Oh yeah definitely makes sense to fix this! I [tested a snippet](https://gitter.im/rust-impl-period/WG-libs-simd?at=59f3cc24e44c43700a887160) which I think may have been a reduction of this? It looks like this is fixed in LLVM 5 so this may be blocked on https://github.com/rust-lang/rust/issues/43370

**Comment by hdevalence** [comment] 2017-10-30 19:25
Building the branch mentioned in that issue and using that as the local Rust toolchain fixed the issue for me.

**Comment by hdevalence** [comment] 2017-12-12 20:02
Update: using the current nightly Rust and the current `stdsimd` has stopped working on `skylake-avx512`.

**Comment by gnzlbg** [comment] 2017-12-12 20:07
Does it work with a previous `stdsimd` version but the current nightly Rust? 

Do you have a reproducer? Does it fail to compile, at run-time, etc?

**Comment by hdevalence** [comment] 2017-12-15 19:35
Oops, sorry, I missed this.  I guess you reproduced it; my test case is this AVX2 code: https://github.com/isislovecruft/curve25519-dalek/pull/94

It doesn't use any 512-bit vectors, but there's a mild performance increase when using AVX512VL since the increase in registers avoids spills.

**Comment by gnzlbg** [comment] 2017-12-15 21:10
I’ll try to add a build bot that checks this.

**Comment by alexcrichton** [comment] 2018-02-11 16:26
I believe this was fixed by https://github.com/rust-lang/rust/pull/47828

**Closed by alexcrichton** 2018-02-11 16:26 UTC
Labels: A-llvm, A-x86
