### ISSUE TITLE
Mismatch between parameters to is_target_feature_detected! and target_feature

### ISSUE THREAD

**Issue by Cocalus** [rust-lang-nursery/stdsimd#347] opened 2018-03-07 00:23 UTC
There may be a very good reason for this but it seems odd that 

```rust
#[target_feature(enable = "avx2,sse4.2,lzcnt,popcnt")]
unsafe fn myfunction() {
...
}
```
Works but to safely dynamically call it we need
```rust
    if is_target_feature_detected!("avx2") && is_target_feature_detected!("sse4.2") && is_target_feature_detected!("lzcnt") && is_target_feature_detected!("popcnt") {
        unsafe {myfunction()}
    } else {
        myportablefunction()
    }
```

It would seem nicer if 
```rust
    if is_target_feature_detected!("avx2,sse4.2,lzcnt,popcnt") {
        unsafe {myfunction()}
    } else {
        myportablefunction()
    }
```
worked. Though it might need to be called is_target_features_detected

Also is "is_target_feature_detected!" supposed to compile out if it's statically true with the current RUSTFLAGS? I thought it did but I was finding evidence that it wasn't working so I had to cfg a block on target_feature

```rust
    #[cfg(all(target_arch = "x86_64", target_feature = "avx2",target_feature = "sse4.2", target_feature = "lzcnt", target_feature = "popcnt"))]
    {
         return unsafe {myfunction()};
    }
    if is_target_feature_detected!("avx2") && is_target_feature_detected!("sse4.2") && is_target_feature_detected!("lzcnt") && is_target_feature_detected!("popcnt") {
        unsafe {myfunction()}
    } else {
        myportablefunction()
    }
```

Also it would be nice, if bad cfg target_feature's would warn or error instead of compiling without issue.

Stuff like
```rust
#[cfg(target_feature = "sse3")] //meant ssse3
#[cfg(target_feature = "avx2,sse4.2,lzcnt,popcnt")]
```

**Comment by gnzlbg** [comment] 2018-03-07 07:30
> Also is "is_target_feature_detected!" supposed to compile out if it's statically true with the current RUSTFLAGS? 

Yes. Do you have a reproducer? If so could you file an issue with it?

> Also it would be nice, if bad cfg target_feature's would warn or error instead of compiling without issue.

This is also the case (otherwise fill a bug, with a reproducer). The problem is that both `sse3` and `ssse3` are valid target features, so there is nothing that we can do for you here. In your second example, all target features look to be valid as well. 

-- 

I am closing this (please fill issues for the bugs), and opening an issue to allow `is_target_feature_detected!("avx2,sse4.2,lzcnt,popcnt")`.

**Closed by gnzlbg** 2018-03-07 07:30 UTC
