### ISSUE TITLE
Release 0.0.3

### ISSUE THREAD

**Issue by AdamNiederer** [rust-lang-nursery/stdsimd#160] opened 2017-10-28 03:57 UTC
stdsimd has made a lot of progress since 0.0.2, has become quite usable for experimental projects, and is already a huge step up from inline assembly. I'm currently using it in [base100](https://github.com/AdamNiederer/base100) to make encoding absurdly fast, but I've had to submodule it to use most features. Could we get an interstitial 0.0.x release while we await work on stabilization?

**Comment by alexcrichton** [comment] 2017-10-28 12:49
Thanks for the report! I think this is a dupe of https://github.com/rust-lang-nursery/stdsimd/issues/142, and I also think we're mostly all set and good to go! (just doing some final things here and there)

**Closed by alexcrichton** 2017-10-28 12:49 UTC
