### ISSUE TITLE
Portable math functions don't get inlined

### ISSUE THREAD

**Issue by CryZe** [rust-lang-nursery/stdsimd#523] opened 2018-07-13 00:47 UTC
```rust
#![feature(stdsimd)]

use std::simd::f32x2;

pub fn fma(a: f32x2, b: f32x2, c: f32x2) -> f32x2 {
    a.fma(b, c)
}

pub fn abs(a: f32x2) -> f32x2 {
    a.abs()
}

pub fn sin(a: f32x2) -> f32x2 {
    a.sin()
}

pub fn sqrt(a: f32x2) -> f32x2 {
    a.sqrt()
}
````
Gets compiled to this:
```asm
example::fma:
  push rbx
  sub rsp, 32
  mov rbx, rdi
  mov rax, qword ptr [rsi]
  mov rdx, qword ptr [rdx]
  mov rcx, qword ptr [rcx]
  mov qword ptr [rsp + 8], rax
  mov qword ptr [rsp + 16], rdx
  mov qword ptr [rsp + 24], rcx
  lea rsi, [rsp + 8]
  lea rdx, [rsp + 16]
  lea rcx, [rsp + 24]
  call <core::coresimd::ppsv::v64::f32x2 as core::coresimd::ppsv::codegen::fma::FloatFma>::fma@PLT
  mov rax, rbx
  add rsp, 32
  pop rbx
  ret

example::abs:
  push rbx
  sub rsp, 16
  mov rbx, rdi
  mov rax, qword ptr [rsi]
  mov qword ptr [rsp + 8], rax
  lea rsi, [rsp + 8]
  call <core::coresimd::ppsv::v64::f32x2 as core::coresimd::ppsv::codegen::abs::FloatAbs>::abs@PLT
  mov rax, rbx
  add rsp, 16
  pop rbx
  ret

example::sin:
  push rbx
  sub rsp, 16
  mov rbx, rdi
  mov rax, qword ptr [rsi]
  mov qword ptr [rsp + 8], rax
  lea rsi, [rsp + 8]
  call <core::coresimd::ppsv::v64::f32x2 as core::coresimd::ppsv::codegen::sin::FloatSin>::sin@PLT
  mov rax, rbx
  add rsp, 16
  pop rbx
  ret

example::sqrt:
  push rbx
  sub rsp, 16
  mov rbx, rdi
  mov rax, qword ptr [rsi]
  mov qword ptr [rsp + 8], rax
  lea rsi, [rsp + 8]
  call <core::coresimd::ppsv::v64::f32x2 as core::coresimd::ppsv::codegen::sqrt::FloatSqrt>::sqrt@PLT
  mov rax, rbx
  add rsp, 16
  pop rbx
  ret
```
[Godbolt](https://godbolt.org/g/Tfyvps)

I don't think this is intended.

**Comment by lu-zero** [comment] 2018-07-13 01:11
Looks like #449 is not limited to PowerPC.

**Comment by lu-zero** [comment] 2018-07-13 01:30
https://github.com/rust-lang-nursery/stdsimd/pull/521/commits/26edfc27dece7601dedac760bf5b652c5d2d678e this might help (extend it to the other instruction sets)

**Comment by gnzlbg** [comment] 2018-07-16 15:19
This (https://godbolt.org/g/SQnNfN) 

```rust
#![feature(stdsimd)]

use std::simd::f32x2;
pub fn sin(a: f32x2) -> f32x2 {
    a.sin()
}
```

produces the following LLVM IR: 

```llvm
target datalayout = "e-m:e-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"

define void @_ZN7example3sin17h9c036eb2ab1eadaaE(<2 x float>* noalias nocapture sret dereferenceable(8), <2 x float>* noalias nocapture readonly dereferenceable(8) %a) unnamed_addr #0 {
  %arg.i = alloca <2 x float>, align 8
  %1 = bitcast <2 x float>* %a to i64*
  %2 = load i64, i64* %1, align 8
  %3 = bitcast <2 x float>* %arg.i to i8*
  call void @llvm.lifetime.start.p0i8(i64 8, i8* nonnull %3)
  %4 = bitcast <2 x float>* %arg.i to i64*
  store i64 %2, i64* %4, align 8, !noalias !0
  call void @"_ZN97_$LT$core..coresimd..ppsv..v64..f32x2$u20$as$u20$core..coresimd..ppsv..codegen..sin..FloatSin$GT$3sin17hae53fde8f08ed2edE"(<2 x float>* noalias nocapture nonnull sret dereferenceable(8) %0, <2 x float>* noalias nocapture nonnull dereferenceable(8) %arg.i) #2, !noalias !4
  call void @llvm.lifetime.end.p0i8(i64 8, i8* nonnull %3)
  ret void
}

declare void @"_ZN97_$LT$core..coresimd..ppsv..v64..f32x2$u20$as$u20$core..coresimd..ppsv..codegen..sin..FloatSin$GT$3sin17hae53fde8f08ed2edE"(<2 x float>* noalias nocapture sret dereferenceable(8), <2 x float>* noalias nocapture dereferenceable(8)) unnamed_addr #0

declare void @llvm.lifetime.start.p0i8(i64, i8* nocapture) #1

declare void @llvm.lifetime.end.p0i8(i64, i8* nocapture) #1

attributes #0 = { nounwind "probe-stack"="__rust_probestack" }
attributes #1 = { argmemonly nounwind }
attributes #2 = { nounwind }

!0 = !{!1, !3}
!1 = distinct !{!1, !2, !"_ZN4core8coresimd4ppsv3v645f32x23sin17h532ec7bf70ae1d2dE: argument 0"}
!2 = distinct !{!2, !"_ZN4core8coresimd4ppsv3v645f32x23sin17h532ec7bf70ae1d2dE"}
!3 = distinct !{!3, !2, !"_ZN4core8coresimd4ppsv3v645f32x23sin17h532ec7bf70ae1d2dE: %self"}
!4 = !{!3}
```

**Comment by gnzlbg** [comment] 2018-07-16 15:20
cc @rkruppe @alexcrichton any idea why this might not be getting inlined?

**Comment by gnzlbg** [comment] 2018-07-16 15:21
Probably because we are missing `#[inline]` here: https://github.com/rust-lang-nursery/stdsimd/blob/master/coresimd/ppsv/codegen/sin.rs#L52 (and in similar places).

**Comment by gnzlbg** [comment] 2018-07-16 15:22
@CryZe can you try to reproduce with https://github.com/gnzlbg/ppv upstream? The problem should be fixed there.

**Comment by gnzlbg** [comment] 2018-07-16 15:24
FWIW, there is a new clippy lint (https://rust-lang-nursery.github.io/rust-clippy/master/index.html#missing_inline_in_public_items) that detects whether a function, trait method impl, etc. is not marked with `#[inline]` or `#[inline(always)]`, maybe we should enable it for `stdsimd` (and `ppv`) since most of the methods here should be marked with the attribute. That should prevent issues like this from re-appearing in the future.

**Comment by gnzlbg** [comment] 2018-07-18 23:54
This has been fixed upstream.

**Closed by gnzlbg** 2018-07-18 23:54 UTC
Labels: A-portable, bug
